
[workspace]
members = ["crates/cli", "crates/freeze", "crates/to_df", "crates/python"]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021 but not virtual workspaces.
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.package]
version = "0.3.2"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/paradigmxyz/cryo"
repository = "https://github.com/paradigmxyz/cryo"
exclude = [".github/"]

[workspace.dependencies]
cryo_cli = { version = "0.3.2", path = "./crates/cli" }
cryo_freeze = { version = "0.3.2", path = "./crates/freeze" }
cryo_to_df = { version = "0.3.2", path = "./crates/to_df" }

alloy = { version = "0.6.4", features = [
    "full",
    "rpc-types-trace",
    "provider-ws",
    "provider-ipc",
    "provider-debug-api",
    "provider-trace-api",
    "transport-ipc-mock",
] }
anstyle = "1.0.10"
async-trait = "0.1.86"
chrono = { version = "0.4.39", features = ["serde"] }
clap_cryo = { version = "4.3.21-cryo", features = [
    "derive",
    "color",
    "unstable-styles",
] }
colored = "2.2.0"
color-print = "0.3.7"
eyre = "0.6.12"
futures = "0.3.31"
governor = "0.8.0"
hex = "0.4.3"
heck = "0.5.0"
indexmap = "2.7.1"
indicatif = "0.17.11"
lazy_static = "1.5.0"
mesc = "0.1.4"
polars = { version = "0.38.3", features = [
    "parquet",
    "string_encoding",
    "polars-lazy",
    "lazy",
    "binary_encoding",
    "json",
    "dtype-struct",
] }
prefix-hex = "0.7.1"
pyo3 = { version = "0.20.3", features = ["extension-module"] }
pyo3-build-config = "0.20.3"
pyo3-asyncio = { version = "0.20.0", features = ["tokio-runtime"] }
pyo3-polars = "0.12.0"
rand = "0.8.5"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "1.0.69"
thousands = "0.2.0"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "sync"] }

[profile.dev]
incremental = true
debug = 1
codegen-units = 32
